In [16]:
import numpy as np

In [17]:
p=np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])

In [18]:
product = np.matmul(p, q)


In [19]:
print("Product of 2 Matrices p and q is = ")
print(product)

Product of 2 Matrices p and q is = 
[[16 19]
 [26 31]]


In [20]:
covmat=np.cov(p,q)


In [21]:
print("Covariance of matrices P and Q is =")
print(covmat)

Covariance of matrices P and Q is =
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
